name: Server CI

on:
  pull_request:
    paths:
      - "fogcms-server/**"

jobs:
  format:
    name: Format
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: fogcms-server
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: "1.22"
      - run: gofmt -w .

  lint:
    name: Lint
    runs-on: ubuntu-latest
    needs: format
    defaults:
      run:
        working-directory: fogcms-server
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: "1.22"
      - run: go vet ./...

  test:
    name: Tests
    runs-on: ubuntu-latest
    needs: lint
    defaults:
      run:
        working-directory: fogcms-server
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: "1.22"
      - run: go test ./... -race

  build:
    name: Build
    runs-on: ubuntu-latest
    needs: test
    defaults:
      run:
        working-directory: fogcms-server
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: "1.22"
      - run: go build ./cmd/api
